import { UserRole } from "@prisma/client";

export const permissions = {
    auth: {
        viewProfile: "auth:view_profile",
        updateProfile: "auth:update_profile",
        manage2fa: "auth:manage_2fa",
        viewLoginHistory: "auth:view_login_history",
    },
    product: {
        read: "product:read",
        create: "product:create",
        update: "product:update",
        delete: "product:delete",
        manageCategories: "product:manage_categories",
        manageInventory: "product:manage_inventory",
    },
    quote: {
        create: "quote:create",
        readOwn: "quote:read_own",
        save: "quote:save",
        downloadPdf: "quote:download_pdf",
        convertToOrder: "quote:convert_to_order",
        review: "quote:review",
        approve: "quote:approve",
        reject: "quote:reject",
        editPricing: "quote:edit_pricing",
    },
    gerber: {
        upload: "gerber:upload",
        preview: "gerber:preview",
        downloadOwn: "gerber:download_own",
        deleteOwn: "gerber:delete_own",
        review: "gerber:review",
        approve: "gerber:approve",
        reject: "gerber:reject",
        requestRevision: "gerber:request_revision",
    },
    order: {
        create: "order:create",
        readOwn: "order:read_own",
        cancelOwn: "order:cancel_own",
        reorder: "order:reorder",
        downloadInvoice: "order:download_invoice",
        downloadReport: "order:download_report",
        readAll: "order:read_all",
        updateStatus: "order:update_status",
        assignProduction: "order:assign_production",
        updateShipping: "order:update_shipping",
    },
    payment: {
        pay: "payment:pay",
        readOwn: "payment:read_own",
        downloadReceipt: "payment:download_receipt",
        readAll: "payment:read_all",
        verify: "payment:verify",
        refund: "payment:refund",
        manageGateways: "payment:manage_gateways",
    },
    support: {
        createTicket: "support:create_ticket",
        replyOwnTicket: "support:reply_own_ticket",
        closeOwnTicket: "support:close_own_ticket",
        manageTickets: "support:manage_tickets",
        manageLiveChat: "support:manage_live_chat",
    },
    notification: {
        readOwn: "notification:read_own",
        send: "notification:send",
        broadcast: "notification:broadcast",
        sendPromotionalEmail: "notification:send_promotional_email",
    },
    customer: {
        read: "customer:read",
        verify: "customer:verify",
        block: "customer:block",
        unblock: "customer:unblock",
    },
    production: {
        moveToProduction: "production:move_to_production",
        assignEngineer: "production:assign_engineer",
        assignQc: "production:assign_qc",
        updateProgress: "production:update_progress",
    },
    coupon: {
        create: "coupon:create",
        update: "coupon:update",
        delete: "coupon:delete",
    },
    review: {
        approve: "review:approve",
        deleteSpam: "review:delete_spam",
    },
    shipping: {
        generateLabel: "shipping:generate_label",
        manageCarriers: "shipping:manage_carriers",
        manageRules: "shipping:manage_rules",
    },
    admin: {
        create: "admin:create",
        update: "admin:update",
        delete: "admin:delete",
        suspend: "admin:suspend",
        assignPermissions: "admin:assign_permissions",
    },
    role: {
        create: "role:create",
        update: "role:update",
        delete: "role:delete",
        assignPermissions: "role:assign_permissions",
    },
    system: {
        manageSettings: "system:manage_settings",
        manageBranding: "system:manage_branding",
        manageSmtp: "system:manage_smtp",
        manageSecurity: "system:manage_security",
        maintenanceMode: "system:maintenance_mode",
        monitorHealth: "system:monitor_health",
    },
    pricing: {
        manageFormula: "pricing:manage_formula",
        manageMaterials: "pricing:manage_materials",
        manageLayers: "pricing:manage_layers",
        manageAssembly: "pricing:manage_assembly",
        manageShipping: "pricing:manage_shipping",
    },
    localization: {
        manageCurrency: "localization:manage_currency",
        manageLanguage: "localization:manage_language",
        manageCountry: "localization:manage_country",
        manageTaxRules: "localization:manage_tax_rules",
    },
    analytics: {
        revenue: "analytics:revenue",
        customer: "analytics:customer",
        product: "analytics:product",
        country: "analytics:country",
        conversion: "analytics:conversion",
        marketing: "analytics:marketing",
    },
    cms: {
        manageBlogs: "cms:manage_blogs",
        managePages: "cms:manage_pages",
        manageFaqs: "cms:manage_faqs",
        manageNews: "cms:manage_news",
        manageAnnouncements: "cms:manage_announcements",
    },
    security: {
        viewLoginLogs: "security:view_login_logs",
        viewActivityLogs: "security:view_activity_logs",
        viewSecurityEvents: "security:view_security_events",
        viewFailedLogins: "security:view_failed_logins",
        viewSuspiciousActivities: "security:view_suspicious_activities",
    },
    backup: {
        create: "backup:create",
        restore: "backup:restore",
        download: "backup:download",
    },
    audit: {
        readAll: "audit:read_all",
    },
} as const;

export type Permission = string;

const allPermissions = Object.values(permissions).flatMap((group) => Object.values(group)) as Permission[];

export const permissionCatalog: { key: Permission; group: string; description: string }[] = Object.entries(permissions).flatMap(
    ([group, entries]) =>
        Object.values(entries).map((key) => ({
            key: key as Permission,
            group,
            description: (key as string).replace(`${group}:`, "").replace(/_/g, " "),
        })),
);

export const rolePermissionMap: Record<UserRole, Permission[]> = {
    CUSTOMER: [
        permissions.auth.viewProfile,
        permissions.auth.updateProfile,
        permissions.auth.manage2fa,
        permissions.auth.viewLoginHistory,
        permissions.product.read,
        permissions.quote.create,
        permissions.quote.readOwn,
        permissions.quote.save,
        permissions.quote.downloadPdf,
        permissions.quote.convertToOrder,
        permissions.gerber.upload,
        permissions.gerber.preview,
        permissions.gerber.downloadOwn,
        permissions.gerber.deleteOwn,
        permissions.order.create,
        permissions.order.readOwn,
        permissions.order.cancelOwn,
        permissions.order.reorder,
        permissions.order.downloadInvoice,
        permissions.order.downloadReport,
        permissions.payment.pay,
        permissions.payment.readOwn,
        permissions.payment.downloadReceipt,
        permissions.support.createTicket,
        permissions.support.replyOwnTicket,
        permissions.support.closeOwnTicket,
        permissions.notification.readOwn,
    ],
    ADMIN: [
        permissions.product.read,
        permissions.product.create,
        permissions.product.update,
        permissions.product.delete,
        permissions.product.manageCategories,
        permissions.product.manageInventory,
        permissions.quote.review,
        permissions.quote.approve,
        permissions.quote.reject,
        permissions.quote.editPricing,
        permissions.gerber.review,
        permissions.gerber.approve,
        permissions.gerber.reject,
        permissions.gerber.requestRevision,
        permissions.order.readAll,
        permissions.order.updateStatus,
        permissions.order.assignProduction,
        permissions.order.updateShipping,
        permissions.customer.read,
        permissions.customer.verify,
        permissions.customer.block,
        permissions.customer.unblock,
        permissions.production.moveToProduction,
        permissions.production.assignEngineer,
        permissions.production.assignQc,
        permissions.production.updateProgress,
        permissions.payment.readAll,
        permissions.payment.verify,
        permissions.payment.refund,
        permissions.support.manageTickets,
        permissions.support.manageLiveChat,
        permissions.coupon.create,
        permissions.coupon.update,
        permissions.coupon.delete,
        permissions.review.approve,
        permissions.review.deleteSpam,
        permissions.notification.send,
        permissions.notification.broadcast,
        permissions.notification.sendPromotionalEmail,
        permissions.shipping.generateLabel,
        permissions.shipping.manageCarriers,
    ],
    SUPER_ADMIN: allPermissions,
};

export const hasPermission = (role: UserRole, permission: Permission) => {
    return rolePermissionMap[role]?.includes(permission) ?? false;
};
